### ISSUE TITLE
go build/get can't find vendored open-golang dependency

### ISSUE THREAD

**Issue by mcandre** [skratchdot/open-golang#12]
I've had success in the past vendoring dependencies with git submodules (e.g. in my https://github.com/mcandre/go-ios7crypt project). However, when I try to vendor open-golang in my DuckDuckGo command line launcher project, something breaks. Neither `go build` nor `go get` work for ddg.

Source: https://github.com/mcandre/mcandre/tree/master/go/ddg

Am I doing something wrong?

**Comment by mcandre** [comment]
I was :P

HEAD now has a working vendor setup using git submodules, over and out.

**Comment by skratchdot** [comment]
Sorry I didn't address this.  Thanks for looking into this and closing the ticket @mcandre !
