### ISSUE TITLE
new Window not tab

### ISSUE THREAD

**Issue by Tarektouati** [skratchdot/open-golang#13]
Hey is it possible to open url in a new Window not  in a tab ?

**Comment by skratchdot** [comment]
I'm not sure if there's a cross browser way to do this.  For me, firefox opens links in a new window, and chrome opens them in a new tab.  On osx, I've played around with various switches to the `open` tool, and I haven't found a way

**Comment by Tarektouati** [comment]
Okay thanks for the reply

**Comment by skratchdot** [comment]
@Tarektouati -

Actually, for OSX, there does appear to be a way to have Chrome open things in a new window:

```
open -n -a "Google Chrome" --args "https://www.google.com" --new-window
```

I need to think about how this would work in a cross platform way (or if it's even possible).

Currently, this go-wrapper does not allow passing arguments, but perhaps that's a feature that should be added.  I think if we add "passing arguments", it'd still be the user of the library to pass the correct arguments to "open a new window".

I'll think about it some.  Going to re-open just in case I ever get around to adding new features...
