### ISSUE TITLE
On Windows CMD shell opens briefly

### ISSUE THREAD

**Issue by Mobiustic** [skratchdot/open-golang#15]
Hi, I am a newb to both golang and Windows development so forgive a possibly stupid question.

First, this is a very useful library - thanks to dev(s).

Invoking Start or Run causes a blank CMD shell to briefly appear with focus. It does go away quickly but seems to upset users.

Is there a way to suppress the CMD shell in a way that at least it is not visible to the user. Something appearing on the taskbar would be fine.

Thank you!

**Comment by xiegeo** [comment]
I never seen this. Do you have sample code to reproduce the behavior? Also which version of windows are you using?

**Comment by hugows** [comment]
Isn't this package replaced by https://godoc.org/github.com/pkg/browser nowadays?

**Comment by Mobiustic** [comment]
I believe I mistakenly attributed this minor issue to open-golang when it now appears to be more of a browser / system issue.

The golang executable is being used as a custom protocol handler. The exe when run from a test does not, in fact, exhibit the problem behavior.

The CMD shell is only appearing when the executable is called from the browser.

It does not happen on other platforms and I now believe its probably an artifact of Windows system behavior.

Incidentally, this seems to be related but I have not had a chance to follow up: http://www.joeware.net/freetools/tools/quiet/index.htm

Apologies for finger pointing.
