### ISSUE TITLE
Opening folders does not work on Windows

### ISSUE THREAD

**Issue by idbrii** [skratchdot/open-golang#19]
I can get open-golang to open files (a pdf in my browser) and urls, but not folders. I want to open a folder in Windows Explorer.

The readme says:

> Open a file, directory, or URI using the OS's default application

so I assume directories should be supported.

    // In cmd.exe, I setup and run the program.
    // Install dependencies:
    //   go get "github.com/skratchdot/open-golang/open/..."
    // Ensure directory exists:
    //   mkdir c:\scratch
    // Build:
    //   go build open_with_open.go
    //   open_with_open.exe
    package main

    import (
        "fmt"
        "github.com/skratchdot/open-golang/open"
    )

    func main() {
        // None of these options work.
        exe_path := `c:/scratch`
        exe_path = `c:/scratch/`
        exe_path = `c:\scratch`
        // I see this output.
        fmt.Printf("Trying to open folder: %v\n", exe_path)
        // nothing happens except command prompt loses focus. I see no error.
        err := open.Start(exe_path)
        if err != nil {
            panic(err)
        }
    }

I want the equivalent of this in a command prompt:

    start c:\scratch

Is open-golang the wrong package? (I'm new to golang, so forgive my ignorance.)

**Comment by idbrii** [comment]
go version go1.12 windows/amd64

**Comment by seanhoughton** [comment]
I've created a PR which fixes this problem for folders. I'm not sure what it affect it has on other URL types, but I need it to work with folders so...

https://github.com/skratchdot/open-golang/pull/20

**Comment by skratchdot** [comment]
Sorry about this. I missed this issue, and the PR.  Seems like this was introduced in #17.  I've reverted those changes so opening folders starts working again.

**Comment by skratchdot** [comment]
this was fixed by #20 and #22
