### ISSUE TITLE
imported and not used: "syscall"

### ISSUE THREAD

**Issue by fpsqdb** [skratchdot/open-golang#21]
Location: `open\exec_windows.go:10:2`

**Comment by jakubknejzlik** [comment]
Just FYI, but introduced here: https://github.com/skratchdot/open-golang/commit/da5c36ab639374d3b0018877b3fd191a97cfcef7

**Comment by mkgti** [comment]
exec_windows.go:10：2  Notes  “syscall”    //“syscall”

goplay   SUCCEEDED

**Comment by lucymhdavies** [comment]
https://github.com/skratchdot/open-golang/pull/22 looks like it should fix it

**Comment by skratchdot** [comment]
closing b/c this is fixed by #22
