### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by henjue** [skratchdot/open-golang#9]
```go
open.Run("https://coding.net/oauth_authorize.html?client_id=123456&redirect_uri=http://127.0.0.1/callback&response_type=code&scope=user,project")
```
Browser is URL :https://coding.net/oauth_authorize.html?client_id=123456^&redirect_uri=http://127.0.0.1/callback^&response_type=code^&scope=user,project

I don't think it should be replaced, or it's a mistake here.
 OS:windows

**Comment by skratchdot** [comment]
Which version of windows are you using?  The code causing that is:

https://github.com/skratchdot/open-golang/blob/master/open/exec_windows.go#L17

That code was added to fix #6 

Not sure if this commit re-broke #6: https://github.com/skratchdot/open-golang/commit/94271da2d00f6d85c21257ed16a626332443095d

**Comment by skratchdot** [comment]
I'd be interested to see if `RunWith` works.  It appears run32dll is only used for `Run` not `RunWith`.  That appears to be a bug.  Perhaps I can remove `cleanInput()` when using run32dll.

**Comment by lawrencecraft** [comment]
Hi,

I replicated this issue on my machine. FWIW, I'm on Windows 7 with Go 1.5.1. I also was able to successfully open a URL _without_ replacing, so I've submitted a PR.

**Comment by skratchdot** [comment]
Thanks for the PR @lawrencecraft!  I'm going to close this due to aeb1cab633c5e78e9a867c68c9a48933c2caac74
